title: Vyrážíme do země zapadajícího slunce
baseURL: https://kind-murdock-0ac794.netlify.com
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20



